[package]
name = "wf-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
bincode = { version = "2.0.1", features = ["serde"] }
chrono = "0.4.41"
serde = { version = "1.0.219", features = ["derive"] }
serenity = "0.12.4"
smol = "2.0.2"
warframe = "7.0.1"
